### ISSUE TITLE
Lower case primitives malfunctioning

### ISSUE THREAD

**Issue by mattixittam** [nikhilkalige/docblockr#160] opened 2016-01-28 15:18 UTC
The lower case primitives setting doesn't seem to work. All primitive names are made lowercase, as well as all my own classnames, regardless of the setting.

**Comment by mliq** [comment] 2016-07-20 16:16
In my case, they never are lowercase, only title case despite having this option checked in settings.

**Comment by MoritzKn** [comment] 2016-08-09 21:21
In which language does this happen?
At the moment the `lower_case_primitives` setting is only supported for CoffeeScript, Typescript and JavaScript.

**Comment by mliq** [comment] 2016-08-26 17:56
@MoritzKn This happens in JavaScript but I am using the `Babel ES6 JavaScript` grammar which comes from the `language-babel` package (445,942 downloads, so it is not an obscure user base). Thanks if you can support it!

**Comment by MoritzKn** [comment] 2016-08-28 09:05
I will investigate that.

**Comment by MoritzKn** [comment] 2017-03-19 18:18
Sorry for the long delay here. @mliq I tried reproducing this with the language-babel package but without success. Maybe this is just a misunderstanding. What exactly do you mean by "they never are lowercase, only title case"? As far as I can see this makes no difference since the only primitives in JS are `string`, `number`, `object` and `function`. And actual this only applies to `string` and `number`.

**Comment by MoritzKn** [comment] 2017-05-18 18:07
No response, closing. Feel free to comment here if it's still an issue.

**Closed by MoritzKn** 2017-05-18 18:07 UTC
Labels: bug, more-information-needed
