### ISSUE TITLE
React lifecycle method support

### ISSUE THREAD

**Issue by zslabs** [nikhilkalige/docblockr#250] opened 2017-03-16 19:06 UTC
Hi,
Really appreciate all the work that has went into this! Was wondering if supporting [React lifecycle method](https://facebook.github.io/react/docs/react-component.html) was something that had been explored. If I try to use DocBlockr currently:

![kapture 2017-03-16 at 15 04 05](https://cloud.githubusercontent.com/assets/1018402/24014047/d26803ac-0a59-11e7-9ba6-123a4d3df55a.gif)

It does work however if I prepend that with a `function` keyword:

![kapture 2017-03-16 at 15 05 10](https://cloud.githubusercontent.com/assets/1018402/24014085/f9cf0396-0a59-11e7-9472-df5d38f89293.gif)

**Comment by MoritzKn** [comment] 2017-03-17 09:09
As far as I can see that has nothing to do with React, but with the absence of support for the ES6 method shorthand and therefore is a duplicate of #205. Correct me if I am wrong.

**Closed by MoritzKn** 2017-03-17 09:09 UTC

**Comment by zslabs** [comment] 2017-03-17 17:48
@MoritzKn Yep, you're 100% right. Thanks for linking to that issue.
