### ISSUE TITLE
Extra Comment tags being added

### ISSUE THREAD

**Issue by dabates** [NikhilKalige/docblockr#33] opened 2014-10-27 21:41 UTC
Not sure if that's the best "Title" for this bug.

The issue seems to be thus:

I have a Doc Block like this:
```javascript
    /**
     * This service will deal with submission 
     **/
    services.factory("submissionService", ['$http', function($http) {
        // Note: this will change when we send this into the form
        var submitUrl = "http://some.url";
```

Two things happen.. if I go up tot he function declaration, and press enter to have some white space after the { 
I get a single * after the { so it looks like: { *

The same thing happens of I go to the end of the "var" line and press enter.. at the end of the line it adds: // so it looks like:
```javascript
var submitUrl = "http://some.url";// 
```
Now the second is of less consequence than the first.. but thought you would like to know

**Comment by malko** [comment] 2015-05-23 00:05
Can't reproduce with latest atom and docblocker version so i close the issue for now. Feel free to re-open.

**Closed by malko** 2015-05-23 00:05 UTC
