### ISSUE TITLE
method comment template not generating for ES6 class methods

### ISSUE THREAD

**Issue by samarpanB** [nikhilkalige/docblockr#211] opened 2016-08-25 18:24 UTC
The comment generated for this function within an ES6 class looks like below.

/**
     * 
     */
setSelection (itemToSelect) {
        this.selectedTemplate = itemToSelect;
    }

I actually updated the package to the latest. It was working before the update.

Can someone please help ?

**Comment by MoritzKn** [comment] 2016-08-25 19:43
Previously the function parser was a bit loosely, which coursed a bunch of problems with falsely detected functions. Therefore I made a few changes which led to an stricter parser which, as a side effect, removed support for some ES2015 syntax.
I am going to to add support for this shorthand method definitions again.
But because this is an duplicate of #205 I will close this issue.

**Closed by MoritzKn** 2016-08-25 19:43 UTC
Labels: JavaScript

**Comment by samarpanB** [comment] 2016-08-26 08:56
Hi @MoritzKn ,
Is there way to go back to previous version which worked in Atom ?

**Comment by MoritzKn** [comment] 2016-08-26 10:35
@samarpanB
You can go back to an older version with:
```
aom install docblockr@v0.7.4
```
But I would not recoment that
