### ISSUE TITLE
Do not wrap lists.

### ISSUE THREAD

**Issue by jordwalke** [nikhilkalige/docblockr#228] opened 2016-11-21 08:57 UTC
If I have comments like this, they should not be joined onto one line:

```
            /*
             * - List Item.
             * - Another List item.
             */

```

I imagine there could be a setting that configures this, but in general having markdown style lists in comments is very common  (so list items using `-` or `1.`, `2.` etc).

**Comment by MoritzKn** [comment] 2018-05-23 21:05
Duplicate of #296 (This one was actually there first but I overlooked it at first and the other one is a bit more detailed)

**Closed by MoritzKn** 2018-05-23 21:05 UTC
