### ISSUE TITLE
a bug that repeat single line comment with cjk-char when start  a new line

### ISSUE THREAD

**Issue by netmou** [nikhilkalige/docblockr#258] opened 2017-04-18 02:54 UTC
write a comment like ‘//这是一行注释 ’ in a php file  with cjk-char ,then start a new line at the end, the comment will become like follow:
//这是一行注释
//这是一行注释

**Comment by netmou** [comment] 2017-04-18 02:57
env like follow:
atom v16.0
docblockr 0.9.4

**Comment by MoritzKn** [comment] 2018-05-23 21:02
Duplicate of #307

**Closed by MoritzKn** 2018-05-23 21:02 UTC
