### ISSUE TITLE
double 'enter' on block comment

### ISSUE THREAD

**Issue by ppd0523** [nikhilkalige/docblockr#261] opened 2017-04-19 21:13 UTC
when I push one 'enter' or 'tab' first after /**, get twice.
and get 'enter' twice in discription field.

**Comment by MoritzKn** [comment] 2017-05-18 18:46
Thanks for taking the time to report this!
I noticed that this is a duplicate of #202. You may want to subscribe there for updates.

**Closed by MoritzKn** 2017-05-18 18:46 UTC
