### ISSUE TITLE
I'd like to remove type

### ISSUE THREAD

**Issue by tirafesi** [nikhilkalige/docblockr#252] opened 2017-03-23 19:11 UTC
Is there a way to remove ``type``? I'd like the format of the comment to be:

    /**
     * [Method description]
     *
     * @param [Param Name]  [description]
     * @param [Param Name]  [description]
     */

I tried looking at the options, and while I found a way to remove ``description``, I couldn't find a way to remove ``type``. When I run ``javadoc`` with the default ``docblockr`` format, I get the warning:

``warning - @param argument "[TYPE]" is not a parameter name.``

Besides, ``javadoc`` automatically detects the parameter type, so to write it here seems kind of redundant...

**Comment by MoritzKn** [comment] 2017-03-29 18:06
Thanks for reporting, but this is a duplicate of #242

**Closed by MoritzKn** 2017-03-29 18:06 UTC
