### ISSUE TITLE
Uncaught TypeError: type RegExp expected

### ISSUE THREAD

**Issue by need12648430** [nikhilkalige/docblockr#76] opened 2015-04-12 08:59 UTC
Tried to document a method in Haxe 3 and it threw an exception.

Tried several, same problem on all of them.

**Atom Version**: 0.190.0
**System**: Microsoft Windows 7 Home Premium 
**Thrown From**: [docblockr](https://github.com/nikhilkalige/docblockr) package, v0.6.3
### Stack Trace

Uncaught TypeError: type RegExp expected

```
At C:\Users\user\.atom\packages\docblockr\lib\xregexp.js:141

TypeError: type RegExp expected
  at copy (C:\Users\user\.atom\packages\docblockr\lib\xregexp.js:141:19)
  at Function.self.exec (C:\Users\user\.atom\packages\docblockr\lib\xregexp.js:504:18)
  at DocsParser.ActionscriptParser.parse_function (C:\Users\user\.atom\packages\docblockr\lib\docsparser.js:841:27)
  at DocsParser.parse (C:\Users\user\.atom\packages\docblockr\lib\docsparser.js:46:20)
  at DocBlockrAtom.module.exports.DocBlockrAtom.parse_command (C:\Users\user\.atom\packages\docblockr\lib\docblockr-worker.js:268:29)
  at atom-workspace.<anonymous> (C:\Users\user\.atom\packages\docblockr\lib\docblockr-worker.js:64:16)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\user\AppData\Local\atom\app-0.190.0\resources\app\src\command-registry.js:242:29)
  at C:\Users\user\AppData\Local\atom\app-0.190.0\resources\app\src\command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (C:\Users\user\AppData\Local\atom\app-0.190.0\resources\app\node_modules\atom-keymap\lib\keymap-manager.js:521:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (C:\Users\user\AppData\Local\atom\app-0.190.0\resources\app\node_modules\atom-keymap\lib\keymap-manager.js:356:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (C:\Users\user\AppData\Local\atom\app-0.190.0\resources\app\src\window-event-handler.js:180:20)

```
### Commands

```
     -5:01.4 zen:toggle (atom-text-editor.editor)
     -5:01.4 tree-view:show (atom-workspace.workspace.scrollbars-visible-always.theme-seti-syntax.theme-seti-ui)
     -4:59.1 zen:toggle (atom-text-editor.editor)
     -4:59.0 tree-view:toggle (atom-workspace.workspace.scrollbars-visible-always.theme-seti-syntax.theme-seti-ui)
     -4:58.6 zen:toggle (atom-text-editor.editor)
     -4:58.6 tree-view:show (atom-workspace.workspace.scrollbars-visible-always.theme-seti-syntax.theme-seti-ui)
     -4:57.5 zen:toggle (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -4:57.4 tree-view:toggle (atom-workspace.workspace.scrollbars-visible-always.theme-seti-syntax.theme-seti-ui)
     -4:53.1 zen:toggle (atom-text-editor.editor)
     -4:53.1 tree-view:show (atom-workspace.workspace.scrollbars-visible-always.theme-seti-syntax.theme-seti-ui)
     -4:15.8 grammar-selector:show (atom-text-editor.editor)
     -3:55.7 settings-view:install-packages-and-themes (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -3:52.6 core:confirm (atom-text-editor.editor.mini)
     -0:56.1 docblockr:parse-enter (atom-text-editor.editor)
     -0:56.0 editor:newline (atom-text-editor.editor)
     -0:54.8 docblockr:parse-enter (atom-text-editor.editor)
```
### Config

``` json
{
  "core": {
    "themes": [
      "seti-ui",
      "seti-syntax"
    ],
    "disabledPackages": [
      "minimap"
    ]
  },
  "docblockr": {}
}
```
### Installed Packages

``` coffee
# User
autocomplete-plus, v2.9.0
docblockr, v0.6.3
haxe, v0.6.1
language-haxe, v0.2.1
linter, v0.12.0
seti-syntax, v0.3.3
seti-ui, v0.6.3
Zen, v0.11.4

# Dev
No dev packages
```

**Comment by mlms13** [comment] 2015-05-11 22:59
Same error, also with Haxe:

- haxe, `v0.6.1`
- language-haxe, `0.2.1`
- docblockr, `v0.6.3`
- a variety of other packages that are probably less relevant

**Comment by develephant** [comment] 2015-08-30 21:28
It's certainly not ideal, but if you switch the syntax to JavaScript it seems to work.

Cheers.

**Comment by FranklinWaller** [comment] 2015-12-10 12:08
The issue is still here..

**Comment by mockey** [comment] 2015-12-21 01:36
The Typescript parser actually seems to work quite well for Haxe. At least it doesn't throw exceptions but correctly detects param names and types. As a quick hack I removed `source_lang == "haxe"` here:
https://github.com/nikhilkalige/docblockr/blob/master/lib/docblockr-worker.js#L811
and added:
```
else if((source_lang === "haxe"))
  return new Parsers.TypescriptParser(settings);`
```
Cheers.

**Comment by TheSHEEEP** [comment] 2016-02-16 14:26
Issue still persists...

Thanks for the workaround, though.

**Comment by MoritzKn** [comment] 2021-07-26 10:54
I am closing this in an attempted to clean up the issue tracker. If this is still a bug to this day, Let me know or open a new issue.

**Closed by MoritzKn** 2021-07-26 10:54 UTC
Labels: bug
