### ISSUE TITLE
PHP Variable Documentation

### ISSUE THREAD

**Issue by jwhulette** [nikhilkalige/docblockr#264] opened 2017-05-05 17:32 UTC
When adding documentation to a PHP variable:

protected $var1
private $var2

The docboc for a function appears, not for variable documentation.

Should be:
    /**
     * @var object A Carbon date object
     */
    private $reportEnd;

Actually happens:
/**
 * [__construct description]
 *
 * @method __construct
 *
 * @param  [type] $adwordsId [description]
 * @param  [type] $range [description]
 * @param  [type] $clientId [description]
 */
    private $test;

It seems to pick up the constructor, but not the variable.

**Comment by UziTech** [comment] 2017-05-18 18:23
This seems to be a duplicate of #255 

A pull request as just been merged to solve this #259

**Comment by MoritzKn** [comment] 2017-05-18 18:31
No response, closing. Feel free to comment here if it's still an issue.

**Closed by MoritzKn** 2017-05-18 18:31 UTC
