### ISSUE TITLE
Support for ES6 object function declaration

### ISSUE THREAD

**Issue by piecedigital** [nikhilkalige/docblockr#239] opened 2017-01-16 09:39 UTC
The auto complete for functions doesn't work unless it's explicitly declared as function.
It'd be nice if it did.

```
{
  /**
   * [foo description]
   * @return {[type]} [description]
   */
  foo: function() {...},
  /**
   * 
   */
  foo() {...}
}
```

**Comment by MoritzKn** [comment] 2017-01-16 17:49
Thanks for reporting, but his is a duplicate of #205.

**Closed by MoritzKn** 2017-01-16 17:49 UTC
