### ISSUE TITLE
/** enter doesn't work

### ISSUE THREAD

**Issue by apolytos** [nikhilkalige/docblockr#232] opened 2016-12-04 12:44 UTC
[Enter steps to reproduce below:]  1. ... 2. ...  **Atom Version**: 1.12.6 **Electron Version**: 1.3.9 **System**: Microsoft Windows 10 Pro **Thrown From**: [docblockr](https://github.com/nikhilkalige/docblockr) package, v0.9.0   ### Stack Trace  Uncaught TypeError: Cannot read property 'replace' of undefined  ``` At C:\Users\apoly\.atom\packages\docblockr\lib\docsparser.js:353  TypeError: Cannot read property 'replace' of undefined     at DocsParser.get_definition (C:\Users\apoly\.atom\packages\docblockr\lib\docsparser.js:353:20)     at DocBlockrAtom.module.exports.DocBlockrAtom.initialize (C:\Users\apoly\.atom\packages\docblockr\lib\docblockr-worker.js:760:26)     at DocBlockrAtom.module.exports.DocBlockrAtom.parse_command (C:\Users\apoly\.atom\packages\docblockr\lib\docblockr-worker.js:276:12)     at atom-workspace.<anonymous> (C:\Users\apoly\.atom\packages\docblockr\lib\docblockr-worker.js:77:16)     at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\apoly\AppData\Local\atom\app-1.12.6\resources\app.asar\src\command-registry.js:259:29)     at C:\Users\apoly\AppData\Local\atom\app-1.12.6\resources\app.asar\src\command-registry.js:3:59     at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (C:\Users\apoly\AppData\Local\atom\app-1.12.6\resources\app.asar\node_modules\atom-keymap\lib\keymap-manager.js:587:16)     at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (C:\Users\apoly\AppData\Local\atom\app-1.12.6\resources\app.asar\node_modules\atom-keymap\lib\keymap-manager.js:382:22)     at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (C:\Users\apoly\AppData\Local\atom\app-1.12.6\resources\app.asar\src\window-event-handler.js:106:36)     at HTMLDocument.<anonymous> (C:\Users\apoly\AppData\Local\atom\app-1.12.6\resources\app.asar\src\window-event-handler.js:3:59) ```  ### Commands  ```   5x -4:15.8.0 core:backspace (atom-text-editor.editor.mini.is-focused)      -4:09.5.0 core:confirm (atom-text-editor.editor.mini.is-focused)      -2:25.7.0 tree-view:remove (span.name.icon.icon-file-text)      -2:22.5.0 tree-view:add-file (div.header.list-item)   9x -2:05.5.0 core:backspace (atom-text-editor.editor.mini.is-focused)      -1:56 core:confirm (atom-text-editor.editor.mini.is-focused)      -1:42.2.0 tree-view:add-file (div.header.list-item)      -1:39.4.0 core:confirm (atom-text-editor.editor.mini.is-focused)      -1:17.3.0 tree-view:remove (span.name.icon.icon-file-text)      -1:02.4.0 core:select-all (atom-text-editor.editor.is-focused)   2x -1:02.1.0 core:backspace (atom-text-editor.editor.is-focused)      -0:56.9.0 emmet:expand-abbreviation-with-tab (atom-text-editor.editor.is-focused)   2x -0:56.3.0 core:backspace (atom-text-editor.editor.is-focused)      -0:55.3.0 docblockr:parse-enter (atom-text-editor.editor.is-focused)   6x -0:32.8.0 core:backspace (atom-text-editor.editor.is-focused)   2x -0:27 docblockr:parse-enter (atom-text-editor.editor.is-focused) ```  ### Config  ```json {   "core": {     "allowPendingPaneItems": false,     "autoHideMenuBar": true,     "closeEmptyWindows": false,     "customFileTypes": {       "source.ini": [         ".buckconfig",         ".hgrc"       ],       "source.json": [         ".arcconfig",         "BUCK.autodeps"       ],       "source.python": [         "BUCK"       ]     },     "disabledPackages": [       "jquery-snippets",       "background-tips",       "archive-view",       "bookmarks",       "go-to-line",       "metrics",       "sync-settings"     ],     "packagesWithKeymapsDisabled": [       "git-control",       "atom-ternjs"     ],     "telemetryConsent": "no",     "themes": [       "atom-material-ui",       "base16-syntax"     ]   },   "docblockr": {     "simple_mode": true   } } ```  ### Installed Packages  ```coffee # User activate-power-mode, v1.1.0 (active) atom-live-server, v1.2.5 (inactive) atom-material-ui, v1.3.8 (active) autocomplete-project-paths, v2.2.0 (active) base16-syntax, v1.7.0 (active) browser-plus, v0.0.87 (active) color-picker, v2.2.3 (active) docblockr, v0.9.0 (active) emmet, v2.4.3 (active) file-icons, v1.7.25 (active) flex-tool-bar, v0.11.0 (active) git-control, v0.8.2 (inactive) jquery-snippets, v11.0.0 (inactive) linter, v1.11.18 (active) linter-eslint, v8.0.0 (active) linter-jshint, v3.0.1 (active) pigments, v0.37.0 (active) platformio-ide-terminal, v2.2.2 (active) project-manager, v3.3.3 (active) react, v0.16.1 (active) semicolonize, v0.1.1 (inactive) sync-settings, v0.7.2 (inactive) todo-show, v1.8.0 (inactive) tool-bar, v1.0.1 (active) wakatime, v6.0.10 (active) atom-dark-syntax, v0.27.0 (inactive) atom-dark-ui, v0.52.0 (inactive) atom-light-syntax, v0.28.0 (inactive) atom-light-ui, v0.45.0 (inactive) base16-tomorrow-dark-theme, v1.3.0 (inactive) base16-tomorrow-light-theme, v1.3.0 (inactive) one-dark-ui, v1.6.2 (inactive) one-light-ui, v1.6.2 (inactive) one-dark-syntax, v1.5.0 (inactive) one-light-syntax, v1.5.0 (inactive) solarized-dark-syntax, v1.0.5 (inactive) solarized-light-syntax, v1.0.5 (inactive) about, v1.7.0 (active) archive-view, v0.62.0 (inactive) autocomplete-atom-api, v0.10.0 (active) autocomplete-css, v0.13.1 (active) autocomplete-html, v0.7.2 (active) autocomplete-plus, v2.31.4 (active) autocomplete-snippets, v1.11.0 (active) autoflow, v0.27.0 (inactive) autosave, v0.23.1 (active) background-tips, v0.26.1 (inactive) bookmarks, v0.42.0 (inactive) bracket-matcher, v0.82.2 (active) command-palette, v0.39.0 (inactive) deprecation-cop, v0.54.1 (active) dev-live-reload, v0.47.0 (active) encoding-selector, v0.22.0 (active) exception-reporting, v0.40.0 (active) find-and-replace, v0.202.2 (inactive) fuzzy-finder, v1.4.0 (active) git-diff, v1.1.0 (active) go-to-line, v0.31.0 (inactive) grammar-selector, v0.48.2 (active) image-view, v0.60.0 (active) incompatible-packages, v0.26.1 (active) keybinding-resolver, v0.35.0 (active) line-ending-selector, v0.5.0 (active) link, v0.31.2 (inactive) markdown-preview, v0.158.8 (active) metrics, v1.1.2 (inactive) notifications, v0.65.1 (active) open-on-github, v1.2.1 (inactive) package-generator, v1.0.1 (inactive) settings-view, v0.243.1 (active) snippets, v1.0.4 (active) spell-check, v0.68.4 (active) status-bar, v1.4.1 (active) styleguide, v0.47.2 (active) symbols-view, v0.113.1 (inactive) tabs, v0.103.0 (active) timecop, v0.33.2 (active) tree-view, v0.210.0 (active) update-package-dependencies, v0.10.0 (active) welcome, v0.35.1 (active) whitespace, v0.35.0 (active) wrap-guide, v0.38.2 (active) language-c, v0.54.0 (active) language-clojure, v0.22.1 (active) language-coffee-script, v0.48.0 (active) language-csharp, v0.13.0 (active) language-css, v0.40.1 (active) language-gfm, v0.88.0 (active) language-git, v0.15.0 (active) language-go, v0.43.0 (active) language-html, v0.47.1 (active) language-hyperlink, v0.16.1 (active) language-java, v0.24.0 (active) language-javascript, v0.122.0 (active) language-json, v0.18.3 (active) language-less, v0.29.6 (active) language-make, v0.22.2 (active) language-mustache, v0.13.0 (active) language-objective-c, v0.15.1 (active) language-perl, v0.37.0 (active) language-php, v0.37.3 (active) language-property-list, v0.8.0 (active) language-python, v0.45.1 (active) language-ruby, v0.70.2 (active) language-ruby-on-rails, v0.25.1 (active) language-sass, v0.57.0 (active) language-shellscript, v0.23.0 (active) language-source, v0.9.0 (active) language-sql, v0.25.0 (active) language-text, v0.7.1 (active) language-todo, v0.29.1 (active) language-toml, v0.18.1 (active) language-xml, v0.34.12 (active) language-yaml, v0.27.1 (active)  # Dev No dev packages ```

**Comment by MoritzKn** [comment] 2016-12-04 21:52
I guess this is a duplicate of #233. I will close this issue because of it's messed up formatting.

**Closed by MoritzKn** 2016-12-04 21:52 UTC
