### ISSUE TITLE
Not work with es6

### ISSUE THREAD

**Issue by eagle7410** [nikhilkalige/docblockr#246] opened 2017-02-14 09:30 UTC
Screen http://joxi.ru/VrwYXv0sE39O2X.
Os ubuntu 64x
OS version screen
http://joxi.ru/Q2Kel9MiPEKarj

**Comment by MoritzKn** [comment] 2017-02-14 11:44
Thanks for reporting, but this is a duplicate of #205.

**Closed by MoritzKn** 2017-02-14 11:44 UTC
