### ISSUE TITLE
Auto function comment are not ceated

### ISSUE THREAD

**Issue by indolentdeveloper** [nikhilkalige/docblockr#151] opened 2015-12-22 06:42 UTC
in case of function defined using assignment, function comments are not generated while press of tab.

var f = function (data) {
}

I don't get comments generated for this method. I am using atom.

**Comment by dwhieb** [comment] 2016-01-18 07:41
I'm having the same issue. v0.7.3

**Comment by phil-r** [comment] 2016-01-28 14:53
Same here docblockr v0.7.3 atom v1.4.1

**Comment by MoritzKn** [comment] 2016-08-10 11:35
I can't reproduce this..
Version 0.7.4 made quite a few changed to the JS function parser, so this my be solved already.
Could you please test if this is still reproducible in Version 0.8.0.

**Comment by dwhieb** [comment] 2016-08-10 15:15
Seems to be working fine now.

**Comment by MoritzKn** [comment] 2016-08-10 16:43
Perfect! I will close this issue for now. Feel free to reopen if it occurs again.

**Closed by MoritzKn** 2016-08-10 16:43 UTC
