### ISSUE TITLE
spacer_between_sections not keeping config setting.

### ISSUE THREAD

**Issue by garygreen** [nikhilkalige/docblockr#208] opened 2016-08-18 10:34 UTC
Whenever I change this to "after_description" and restart atom, it removes the value. Also when I change it for the first time it doesn't seem to work either.

![docblockr-saving-issue](https://cloud.githubusercontent.com/assets/1702638/17770835/c059d3e2-6537-11e6-82bb-dd9d97240f0c.gif)

**Comment by MoritzKn** [comment] 2016-09-08 22:52
This basically is a duplicate of #145

**Closed by MoritzKn** 2016-09-08 22:52 UTC
Labels: bug
